name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build the Docker image - AMD64
      run: docker build --build-arg opts="CGO_ENABLED=0 GOARCH=amd64" --tag stephanus42/lemi011b:amd64 --file build/docker/Dockerfile .
    - name: Push the Docker image - AMD64
      run: docker push stephanus42/lemi011b:amd64
      
    - name: Build the Docker image - ARMV7
      run: docker build --build-arg opts="CGO_ENABLED=0 GOARCH=arm GOARM=7" --tag stephanus42/lemi011b:armv7 --file build/docker/Dockerfile .
    - name: Push the Docker image - ARMV7
      run: docker push stephanus42/lemi011b:armv7
      
    - name: Build the Docker image - ARM64
      run: docker build --build-arg opts="CGO_ENABLED=0 GOARCH=arm64" --tag stephanus42/lemi011b:arm64 --file build/docker/Dockerfile .
    - name: Push the Docker image - ARM64
      run: docker push stephanus42/lemi011b:arm64
      
    - name: Create Docker manifest
      run: docker manifest create stephanus42/lemi011b:latest --amend stephanus42/lemi011b:amd64 --amend stephanus42/lemi011b:armv7 --amend stephanus42/lemi011b:arm64
    - name: Push Docker manifest
      run: docker manifest push stephanus42/lemi011b:latest
