name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    
    - name: Build the Docker image - AMD64
      run: docker build --build-arg ARCH="amd64" --tag stephanus42/lemi011b:amd64 --file build/docker/Dockerfile .
    - name: Push the Docker image - AMD64
      run: docker push stephanus42/lemi011b:amd64
      
    - name: Build the Docker image - ARMV7
      run: docker build --build-arg ARCH="arm" --tag stephanus42/lemi011b:arm --file build/docker/Dockerfile .
    - name: Push the Docker image - ARM
      run: docker push stephanus42/lemi011b:arm
      
    - name: Build the Docker image - ARM64
      run: docker build --build-arg ARCH="arm64" --tag stephanus42/lemi011b:arm64 --file build/docker/Dockerfile .
    - name: Push the Docker image - ARM64
      run: docker push stephanus42/lemi011b:arm64
      
    - name: Create Docker manifest
      run: docker manifest create stephanus42/lemi011b:latest --amend stephanus42/lemi011b:amd64 --amend stephanus42/lemi011b:arm --amend stephanus42/lemi011b:arm64
    - name: Push Docker manifest
      run: docker manifest push stephanus42/lemi011b:latest
